spring:
  application:
    name: apigateway
  profiles.active: production

---
spring:
  profiles: development
feign:
  hystrix:
    enabled:true
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.26.150.161:8082/eureka/
 
server:
  port: 8084

---
spring:
  profiles: production
feign:
  hystrix:
    enabled:true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8084
  
turbine:
  aggregator:
    clusterConfig: APIGATEWAY
  appConfig: apigateway

logging:
  level: INFO


