spring:
  application:
    name: apigateway
  profiles.active: production
server:
  contextPath: /gateway
---
spring:
  profiles: development
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://k8s.mrhecloud.com/discovery/eureka/
 
server:
  port: 8084

---
spring:
  profiles: production
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://k8s.mrhecloud.com/discovery/eureka/
server:
  port: 8084
  



