spring:
  application:
    name: bookingservice
  profiles.active: production
server:
  contextPath: /
---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.100.96.171:8761/eureka/
 
server:
  port: 8085

---
spring:
  profiles: production
feign:
  hystrix:
    enabled:true
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.100.96.171:8761/eureka/
server:
  port: 8085

