spring:
  application:
    name: bookingservice
  profiles.active: production

---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.26.150.161:8082/eureka/
 
server:
  port: 8085

---
spring:
  profiles: production
feign:
  hystrix:
    enabled:true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8085

