spring:
  application:
    name: bookingservice
  profiles.active: production
server:
  contextPath: /
---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: http://40.113.121.37/discovery/eureka/
 
server:
  port: 8085

---
spring:
  profiles: production
feign:
  hystrix:
    enabled:true
eureka:
  client:
    serviceUrl:
      defaultZone: http://40.113.121.37/discovery/eureka/
server:
  port: 8085

