spring:
  application:
    name: bookingservice
  profiles.active: production
server:
  contextPath: /bookings
---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: https://k8s.mrhecloud.com/eureka/
 
server:
  port: 8085

---
spring:
  profiles: production
feign:
  hystrix:
    enabled:true
eureka:
  client:
    serviceUrl:
      defaultZone: https://k8s.mrhecloud.com/eureka/
server:
  port: 8085

