spring:
  application:
    name: carservice
  profiles.active: development
server:
  contextPath: /
---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: http://k8s.mrhecloud.com/eureka/
 
server:
  port: 8087

---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://k8s.mrhecloud.com/eureka/
server:
  port: 8087

