spring:
  application:
    name: carservice
  profiles.active: development

---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.26.150.161:8082/eureka/
 
server:
  port: 8087

---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8087

