spring:
  application:
    name: customerservice
  profiles.active: development
server:
  contextPath: /customer
---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.26.150.161:8082/eureka/
 
server:
  port: 8083

---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.100.16:30002/eureka/
server:
  port: 8083

