spring:
  application:
    name: customerservice
  profiles.active: development
server:
  contextPath: /customers
---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: https://k8s.mrhecloud.com/eureka/
 
server:
  port: 8083

---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: https://k8s.mrhecloud.com/eureka/
server:
  port: 8083

