application:
  name: discoveryservice

spring:
  profiles.active: development
server:
  contextPath: /discovery
---
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 80
---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://40.113.121.37/
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 80

