application:
  name: discoveryservice

spring:
  profiles.active: development
server:
  contextPath: /eureka
---
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 8082
---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: https://k8s.mrhecloud.com/eureka/
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 8082

