application:
  name: discoveryservice

spring:
  profiles.active: development

---
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 8082
---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.100.19:30002/eureka/
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 8082

