spring:
  application:
    name: monitoringservice
  profiles.active: production
server:
  contextPath: /monitoring
---
spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: https://k8s.mrhecloud.com/eureka/
 
server:
  port: 8090

---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: https://k8s.mrhecloud.com/eureka/


server:
  port: 8090 
  
turbine:
  appConfig: apigateway
  cluster-name-expression: new String('default') 
  combine-host-port: true



